### ISSUE TITLE
new release 0.3.0

### ISSUE THREAD

**Issue by damian-romero** [damian-romero/damians_code#19]
- [ ] Generalize CP Packager to other platforms #18 
- [ ] Remove unwanted files from CP Packager #15 
- [ ] Update CP Packager Walkthrough.ipynb #20 
- [ ] Add shell script and documentation for `mdchapters` #17
